---

- name: Aparavi Debian 11
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - mysql_server
    - aparavi_appagent
  vars:
    - node_meta_env: 'prod'
    - node_meta_service: 'aparavi'
    - node_meta_component: 'appagent'
    - node_meta_subcomponent: 'app'
    - node_meta_service_instance: 'new_client_name'
    - ssh_client_password_login: true
    - ssh_server_password_login: true
    - sshd_authenticationmethods: "publickey password"
  tasks:
    - name: Flush handlers
      meta: flush_handlers
      tags:
        - mysql_server
    - name: Extra | Retrieving MySQL password
      debug:
        msg: 
          - "Make sure to copy your database root password now."
          - "MySQL root password: {{ mysql_root_password }}"
          - "Make sure you copied the password without the closing quotes"
      tags:
        - mysql_server
    - name: Extra | Retrieving root password (if changed)
      debug:
        msg:
          - "New root password: {{ root_password }}"
          - "It's necessary to have a password for root user. Wazuh 2532."
          - "Compliance: cis 1.5.3; cis_csc 5.1; nist_800_53 CM.1; pci_dss 2.2.4; tsc CC5.2"
      when: root_password is defined
