---

- name: Aparavi Debian 11
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - mysql_server
    - platform
  vars:
    - node_meta_env: 'prod'
    - node_meta_service: 'aparavi'
    - node_meta_component: 'appagent'
    - node_meta_subcomponent: 'app'
    - node_meta_service_instance: 'new_client_name'
    - ssh_client_password_login: true
    - ssh_server_password_login: true
    - sshd_authenticationmethods: "publickey password"
  tasks:
    - name: Flush handlers
      meta: flush_handlers
      tags:
        - mysql_server
    - name: Extra | Retrieving MySQL password
      debug:
        msg: 
          - "Make sure to copy your database root password now."
          - "MySQL root password: {{ mysql_root_password }}"
          - "Make sure you copied the password without the closing quotes"
      tags:
        - mysql_server
    - name: Extra | How to conect to the platform
      debug:
        msg: 
          - "You can connect to the platform using this link: http://{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}:9452"
          - "Aparavi ports: http: 9452, data port: 9455"
          - "You should open both ports in your FW"
          - "Client created with username password: {{ aparavi_platform_client_username }}/{{ aparavi_platform_client_password }}"
          - "Object ID of the Clients account is: {{ aparavi_platform_client_objectid }}. Use it to connect appagent to it."
          - "Platform login credentials: root/root"
      ignore_errors: true
      tags:
        - platform
